version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: backend_api_postgres
    ports:
      - "5332:5432"
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
